In [ ]:
import pandas as pd
import io
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [ ]:
df=pd.read_csv("/content/Churn_Modelling.csv", index_col="RowNumber")
df

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
RowNumber,,,,,,,,,,,,,
1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
df.drop(['CustomerId'],axis=1,inplace=True)
df.drop(['Surname'],axis=1,inplace=True)
df.drop('Age',axis=1,inplace=True)
df.drop('Geography',axis=1,inplace=True)
df.drop('Gender',axis=1,inplace=True)
df

,CreditScore,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
RowNumber,,,,,,,,
1,619,2,0.00,1,1,1,101348.88,1
2,608,1,83807.86,1,0,1,112542.58,0
3,502,8,159660.80,3,1,0,113931.57,1
4,699,1,0.00,2,0,0,93826.63,0
5,850,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...
9996,771,5,0.00,2,1,0,96270.64,0
9997,516,10,57369.61,1,1,1,101699.77,0
9998,709,7,0.00,1,0,1,42085.58,1
9999,772,3,75075.31,2,1,0,92888.52,1
10000,792,4,130142.79,1,1,0,38190.78,0

In [ ]:
df.isnull().sum()

CreditScore        0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
df.duplicated()

RowNumber
1        False
2        False
3        False
4        False
5        False
         ...
9996     False
9997     False
9998     False
9999     False
10000    False
Length: 10000, dtype: bool

In [ ]:
df.describe()

,CreditScore,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,650.528800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,96.653299,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,350.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,584.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,652.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,718.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,850.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [ ]:
scaler=StandardScaler()
df1=pd.DataFrame(scaler.fit_transform(df))
df1

,0,1,2,3,4,5,6,7
0,-0.326221,-1.041760,-1.225848,-0.911583,0.646092,0.970243,0.021886,1.977165
1,-0.440036,-1.387538,0.117350,-0.911583,-1.547768,0.970243,0.216534,-0.505775
2,-1.536794,1.032908,1.333053,2.527057,0.646092,-1.030670,0.240687,1.977165
3,0.501521,-1.387538,-1.225848,0.807737,-1.547768,-1.030670,-0.108918,-0.505775
4,2.063884,-1.041760,0.785728,-0.911583,0.646092,0.970243,-0.365276,-0.505775
...,...,...,...,...,...,...,...,...
9995,1.246488,-0.004426,-1.225848,0.807737,0.646092,-1.030670,-0.066419,-0.505775
9996,-1.391939,1.724464,-0.306379,-0.911583,0.646092,0.970243,0.027988,-0.505775
9997,0.604988,0.687130,-1.225848,-0.911583,-1.547768,0.970243,-1.008643,1.977165
9998,1.256835,-0.695982,-0.022608,0.807737,0.646092,-1.030670,-0.125231,1.977165
9999,1.463771,-0.350204,0.859965,-0.911583,0.646092,-1.030670,-1.076370,-0.505775

In [ ]:
x=df1.iloc[:,:-1].values
x
y=df1.iloc[:,-1].values
y

array([ 1.97716468, -0.50577476,  1.97716468, ...,  1.97716468,
        1.97716468, -0.50577476])

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
print(x_train)
print(len(x_train))
print(x_test)
print(len(x_test))

[[ 0.35666577 -1.04175968  0.69191658 ...  0.64609167 -1.03067011
   0.78766627]
 [-0.53315694 -1.38753759 -1.22584767 ...  0.64609167 -1.03067011
  -0.06991108]
 [ 2.01214989  1.03290776  1.40877711 ...  0.64609167 -1.03067011
   0.87944402]
 ...
 [ 0.31527867  0.68712986 -1.22584767 ... -1.54776799  0.97024255
   1.10636961]
 [ 0.73949648 -0.69598177 -1.22584767 ... -1.54776799  0.97024255
   1.18061717]
 [-0.35726175  0.34135195  0.66374766 ... -1.54776799 -1.03067011
   0.87252042]]
8000
[[ 0.12903671  0.68712986 -1.22584767 ...  0.64609167  0.97024255
   1.39698016]
 [ 1.0705933   0.68712986  1.30149885 ...  0.64609167 -1.03067011
   0.58271672]
 [-1.00910862 -0.35020386  0.66667966 ... -1.54776799 -1.03067011
  -0.0982442 ]
 ...
 [ 0.67741582  1.03290776  0.79590063 ...  0.64609167  0.97024255
   0.66010299]
 [-0.36760852 -1.38753759  0.80596389 ...  0.64609167  0.97024255
  -0.77448836]
 [ 0.83261746 -1.04175968  0.80664905 ...  0.64609167  0.97024255
  -0.43888638]]
2000